Results page
WildCodeSchool/2103-lille-js-p2-g2-heroes pull request #12
Opened 2021-04-27 14:08 UTC by GeorgesFORTRY

2021-04-27 14:13 UTC, frvanco approved these changes, later dismissed

2021-04-28 06:41 UTC, LoicBrassart requested changes
Some Eviiiiiiils, plz fix !

2021-04-28 06:41 UTC, LoicBrassart commented on src/components/Fight.jsx
> +      <img src={location.state.vsHero.image.url} alt="vshéros" />
I don't get where you find these variable, if someone can explain it to me it'd be nice

2021-04-28 06:41 UTC, LoicBrassart commented on src/components/Results.jsx
> +// import ResultCard from './ResultCard';
Deas code

2021-04-28 06:41 UTC, LoicBrassart commented on src/components/Results.jsx
> +    }
Bug spotted: what if `int === spe === str === pow` ?
Fix: give a default attribute to `stat` in the beginning

2021-04-28 06:41 UTC, LoicBrassart commented on src/components/Results.jsx
> +          (hero) => parseInt(hero.powerstats[chosenStat], 10) > 90
What does this filter do ?

2021-04-28 06:41 UTC, LoicBrassart commented on src/components/heroes.json
> +[
- I don't get why you need this file
- It's not a component, so it should not be in `src/components`

2021-04-28 07:40 UTC, frvanco approved these changes

2021-04-28 11:09 UTC, LoicBrassart approved these changes
No more Evil

2021-04-28 11:28 UTC, merged